# Docker Compose file for PostgreSQL and Adminer setup
# https://hub.docker.com/_/postgres

version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: stadsvisioenen
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 10220408
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
